import type { Metadata } from "next";

import Navbar from "@/components/Navbar";
import AuthProvider from "@/context/AuthProvider";
import { Suspense } from "react";
import Loading from "./loading";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
                  <Suspense fallback={<Loading />} >
                    <Navbar/>
                    <AuthProvider>{children}</AuthProvider>
                  </Suspense>


      </body>
    </html>
  );
}
